import Image from 'next/image';
import LogoutButton from '../components/LogoutButton';
import NewUserButton from '../components/NewUserButton';
import { useUser } from '../hooks/useUser';
import './global.css';

export const metadata = {
  title: 'Welcome to lua-desk',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await useUser();

  return (
    <html lang="de">
      <body className="flex flex-col">
        <header className="flex items-center bg-[#f6ebe3] h-16 px-4 relative">
          {/* Logo links */}
          <div className="flex-shrink-0 flex items-center h-full">
            <Image
              src="/logo.webp"
              alt="Logo"
              width={200}
              height={40}
              className="object-contain"
            />
          </div>
          {/* Titel mittig */}
          {/* <h1 className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-center w-full font-bold text-lg">
            {metadata.title}
          </h1> */}
          {/* Buttons rechts */}
          <div className="ml-auto flex items-center gap-2">
            {user?.name === 'Admin' && <NewUserButton />}
            <LogoutButton />
          </div>
        </header>
        <div className="m-2 flex-1">{children}</div>
      </body>
    </html>
  );
}
